# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Replace this title as needed.
title: Indikatoren der deutschen Nachhaltigkeitsstrategie
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging
# Replace my-github-org and open-sdg-data-starter as needed.
remotedatabaseurl: "https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-data-starter"

jekyll_get_json:
  - data: meta
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-data-starter/meta/all.json'
  - data: headlines
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-data-starter/headline/all.json'
  - data: schema
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-data-starter/meta/schema.json'
  - data: reporting
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-data-starter/stats/reporting.json'
  - data: translations
    #json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.2.json'
    json: 'https://JustusCas.github.io/sdg-translations/translations.json'

analytics:
  ga_prod: ''

# Social media accounts.
twitter: 'MyTwitterAccount'

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: DNS-Indikatoren@destatis.de
  suggestions: DNS-Indikatoren@destatis.de
  functional: DNS-Indikatoren@destatis.de

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: nachhaltige-entwicklung-deutschland

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Germany
  adjective: German

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
#frontpage_instructions: Click on each goal, or <span id="jump-to-search"><a>search</a></span>, for Australian statistics for Sustainable Development Goal global indicators.

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /status_summary
    translation_key: menu.status_summary
  - path: /about/
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /status
    translation_key: menu.status

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
    - de
    - en


# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "de"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
#goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals
#goal_image_base: https://nachhaltige-enticklung-deutschland.github.io/open-sdg-site-starter/blob/develop/assets/img/goals
goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals/dns


# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@0.9.1

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css

create_goals:
  layout: goal-by-target

create_indicators:
  layout: indicator


# Mapping
map_options:

  #tileURL: https://api.mapbox.com/styles/v1/mobosse/cjzo8dsnt0bz71cohx8l8etpg/tiles/256/{z}/{x}/{y}?&access_token={accessToken}
  tileURL: https://api.mapbox.com/styles/v1/mobosse/cjzmrn62k0ek11cmgea7a1i1h/tiles/256/{z}/{x}/{y}?&access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjanplNTNhMmQwMTFjM21wNHEzazRlejhwIn0.ecHE5G83cklfW5AXYjI_0A
    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="https://www.bkg.bund.de">&copy; GeoBasis-De / BKG 2019</a>

  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  #Goal 5:
  #colorRange: ['#FFD9D5','#FFC8C1','#FFB6AD','#FFA499','#FF9385','#FF8171','#FF6F5D','#FF5D49','#FF4C35','#FF3A21']
  #Goal 8:
  colorRange: [["#F6E8EC", "#EED3DB", "#E5BFCA", "#DDAAB9", "#D495A8", "#CC8197", "#C46C86", "#BB5775", "#B34264", "#AA2E53", "#A21942"],['#FFD9D5','#FFC8C1','#FFB6AD','#FFA499','#FF9385','#FF8171','#FF6F5D','#FF5D49','#FF4C35','#FF3A21']]

  # Set the color for boundaries that have no data.
  noValueColor:  '#f0f0f0'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  #styleNormal:
    #weight: 1
    #opacity: 1
    #color: #888
    #fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  #styleHighlighted:
    #weight: 1
    #opacity: 1
    #color: #111
    #fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  #styleStatic:
    #weight: 2
    #opacity: 1
    #fillOpacity: 0
    #color: #172d44
    #dashArray: 5,5
map_layers:
  #Country
  #- min_zoom: 5
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4.geojson
    #nameProperty: ctry17nm
    #idProperty: ctry17cd
    #staticBorders: true
    # link: https://hub.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4/data
  #Region
  - min_zoom: 0
    max_zoom: 20
    #serviceUrl: https://opendata.arcgis.com/datasets/33a15b8fd5624dd4800cc33ab5bad761_0.geojson
    serviceUrl: https://g205sdgs.github.io/sdg-indicators/assets/maps/Ländergrenzen_ohne_Seegrenzen.geojson
    nameProperty: GEN
    idProperty: AGS #OBJECTID
    staticBorders: true
    # link: https://hub.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4
  #Local Authority
  #- min_zoom: 6
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.geojson
    #nameProperty: lad16nm
    #idProperty: lad16cd
    #staticBorders: false
    # link: https://hub.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4
  #County
  #- min_zoom: 8
    #max_zoom: 9
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3.geojson
    #nameProperty: cty18nm
    #idProperty: cty18cd
# link: https://hub.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3
